apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-app-name
  labels:
    name: frontend-app-name
    app: demo-quote-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: frontend-app-name
      app: demo-quote-app

  template: 
    metadata:
      name: frontend-app-name
      labels:
        name: frontend-app-name
        app: demo-quote-app
    spec: 
      containers:
         - name: frontend-app
           image: harish343/harish343.me
           ports:
            - containerPort: 80

